name: ngabolang
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.3
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  firebase_storage: ^5.0.1
  flutter_svg: any
  get: ^3.17.1
  google_sign_in: ^4.5.6
  image_picker: ^0.6.7+14
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
